// LAYERPITCH_HELP — dictionnaire des bulles d'aide contextuelle du backstage.
// Séparé de layerpitch-i18n.js volontairement : ce fichier contient du contenu pédagogique
// (explique CE QUE FAIT un contrôle et POURQUOI), pas la traduction de l'interface.
//
// Édité via l'outil dédié (layerpitch-help-editor.html), jamais à la main directement.
// Chargé uniquement par layerpitch-backstage.html — jamais publié sur les pages publiques.
//
// Structure : une zone par section du backstage. Chaque clé correspond à un attribut
// data-help="clé" posé sur un contrôle du backstage.
window.LAYERPITCH_HELP = {
  fr: {
    library: {
      trackMode: "Détermine comment ce morceau réagit à l'écoute : Statique pour une piste simple, Layering vertical pour des couches qui s'ajoutent selon l'intensité, Layering vertical randomisé pour une variation aléatoire à chaque écoute, Séquentiel pour un enchaînement intro / segments / outro.",
      loopableStatic: "Coche si ce morceau statique doit boucler en continu (ambiance). Décoché, il joue une fois puis s'arrête — adapté à un thème ou un générique.",
      bpmMeasuresVerticalRandom: "Le tempo et la mesure de ce morceau, utilisés pour caler la grille de la boucle. Nécessaires ici car ce mode tire des couches aléatoires qui doivent rester synchronisées au rythme.",
      loopPointsVerticalRandom: "Ces repères définissent où la boucle commence et se termine dans le fichier. Toutes les couches (fixe et alternatives) doivent avoir exactement la même durée pour rester synchronisées.",
      defaultLoopCount: "Nombre de fois que la boucle joue par défaut à l'ouverture de la page publique. Le visiteur pourra changer cette valeur lui-même — ce n'est qu'un point de départ.",
      bpmMeasuresSequential: "Le tempo et la mesure de ce morceau. Ils déterminent la durée programmée (en mesures) de l'intro et de chaque segment — voir plus bas.",
      segmentSlotsSection: "Des emplacements enchaînés dans l'ordre défini (1, 2, 3, ... puis retour au premier), en boucle jusqu'à l'outro. Chaque emplacement peut avoir plusieurs alternatives : une est tirée au hasard à chaque passage sur cet emplacement, plutôt qu'un contenu fixe. Il en faut au moins un pour que le morceau soit jouable.",
      slotRepeatCount: "Combien de fois cet emplacement rejoue (en tirant une nouvelle alternative à chaque fois) avant de passer au suivant dans la chaîne. 1 par défaut — augmente pour une structure du genre AABA où le même emplacement doit tourner plusieurs fois de suite.",
      slotContentSource: "Un emplacement peut soit avoir son propre contenu, soit dupliquer (référencer) le pool d'un autre emplacement déjà défini — utile pour une structure comme AABA sans avoir à recharger deux fois les mêmes fichiers en mémoire. L'anti-répétition est alors partagée entre les deux occurrences.",
      loopEngine: "Simple coupe et relance le fichier instantanément à chaque boucle (parfait pour une boucle déjà parfaitement calée). Quantifié permet une transition plus douce, calée sur le tempo, avec une queue sonore qui continue pendant que la boucle suivante démarre déjà.",
      bpmMeasuresQuantized: "Le tempo et la mesure de ce morceau, nécessaires pour caler la boucle quantifiée sur la grille rythmique plutôt que de couper au sample près.",
      loopPointsQuantized: "Ces repères définissent l'intro (jouée une fois), la boucle, et la queue de fin qui se superpose au redémarrage de la boucle suivante.",
      trackDescription: "Texte affiché sur la page publique sous ce morceau, visible quand le visiteur déplie la piste. Sélectionne du texte puis Cmd+K pour y insérer un lien.",
      normalizeVolume: "Corrige automatiquement les écarts de volume entre les fichiers de ce morceau à la conversion (mesure RMS). Utile si tes couches ou alternatives viennent de sessions différentes et sonnent à des niveaux inégaux.",
      fixedLayers: "Les couches qui jouent à chaque cycle de boucle, sans exception — c'est ici que vit l'intro et le cœur rythmique du morceau. Elles doivent toutes faire la même durée que les groupes aléatoires ci-dessous.",
      randomGroups: "Chaque groupe tire au hasard une de ses alternatives à chaque cycle de boucle — c'est ce qui donne l'impression que le morceau ne sonne jamais exactement pareil deux fois. Un groupe peut n'avoir qu'une seule alternative si tu veux juste réserver l'emplacement pour plus tard.",
      groupContentSource: "Un groupe peut soit avoir son propre contenu, soit dupliquer (référencer) le pool d'un autre groupe déjà défini — évite de recharger deux fois les mêmes fichiers en mémoire si deux groupes doivent varier de façon identique. L'anti-répétition est alors partagée entre les deux.",
      batchDropSequential: "Dépose plusieurs fichiers d'un coup : leur rôle (intro / segment / outro) est deviné depuis leur nom de fichier. Vérifie ensuite avec le sélecteur \"Rôle\" de chaque bloc, et corrige si besoin.",
      introSection: "Joue une seule fois, au tout début du morceau, avant que le tirage aléatoire des segments ne démarre.",
      outroSection: "Ne se déclenche que si le visiteur clique sur \"Aller vers la fin\" côté public. Sans outro définie, ce bouton laisse simplement le segment en cours filer jusqu'à sa fin naturelle.",
      layersVertical: "Les couches de ce morceau, de la plus calme à la plus intense — c'est cet ordre qui détermine ce qui s'ajoute quand le visiteur augmente l'intensité sur la page publique.",
      stingers: "Sons courts que le visiteur peut déclencher à la main pendant la lecture (ex. un impact, un sting d'alerte), en plus de la musique en cours — n'affectent pas la boucle principale.",
      implementationNote: "Note libre à ton attention, reprise telle quelle dans la fiche d'implémentation du pack (onglet Packs). Peut contenir du jargon spécifique à un moteur si tu veux (ex. suggestion de RTPC) — contrairement au reste de la fiche, générée en langage neutre.",
    },
    packs: {
      packIllustration: "Image principale affichée en haut de la page publique de ce pack.",
      packWatermark: "Image de fond décorative affichée en transparence derrière tout le contenu de la page — purement esthétique, optionnelle.",
      packPresentation: "Texte de présentation affiché sur la page publique du pack, au-dessus de la liste des morceaux, quand ce pack est lié à un AdReel en français. Sélectionne du texte puis Cmd+K pour y insérer un lien.",
      packPresentationEn: "Version anglaise du texte ci-dessus, affichée quand ce pack est lié à un AdReel en anglais. Si l'une des deux langues n'est pas remplie, l'autre s'affiche par défaut.",
      packBuyable: "Affiche un bouton d'achat sur la page publique du pack. Aucun paiement réel n'est traité aujourd'hui — le lien peut pointer vers autre chose en attendant (mail, formulaire) si besoin.",
      packVideoTestMode: "Ajoute un bouton pour tester une vidéo YouTube/Vimeo : intégrée directement sur la page si le visiteur n'a qu'un écran, ou dans une fenêtre séparée et détachable s'il en a plusieurs. Son coupé par défaut (le visiteur peut le réactiver), pour que le visiteur teste tes morceaux en direct dessus pendant qu'il regarde.",
      implementationSkills: "Réglage global pour tout le site, pas par pack. Coche les logiciels que tu maîtrises (Wwise, FMOD, Unity, Unreal) : un message le mentionnant apparaît sur la page publique de chaque pack, listant uniquement ceux cochés. Aucune case cochée = aucun message affiché.",
      implementationSheetBtn: "Génère à la volée un document (texte + JSON) décrivant le comportement musical de chaque morceau de ce pack en langage neutre — nombre de couches, seuils d'intensité, BPM, points de boucle, structure intro/segment/outro selon le mode. Rien n'est stocké ni publié, uniquement généré au moment où tu cliques.",
      collectionIllustration: "Image principale affichée en haut de la page publique de cette collection.",
      collectionPresentation: "Texte de présentation affiché sur la page publique de la collection, au-dessus de la liste des packs qu'elle contient, quand elle est liée à un AdReel en français.",
      collectionPresentationEn: "Version anglaise du texte ci-dessus. Si l'une des deux langues n'est pas remplie, l'autre s'affiche par défaut.",
      collectionPacks: "Les packs inclus dans cette collection, dans l'ordre d'affichage sur sa page publique. Un même pack peut appartenir à plusieurs collections.",
      packAppearance: "Couleurs de fond et de texte propres à la page de ce pack — indépendantes de celles de l'AdReel qui y renvoie.",
      packTracks: "Les morceaux de la bibliothèque inclus dans ce pack, dans l'ordre d'affichage sur sa page publique.",
    },
    appearance: {
      publishLang: "Langue de l'interface publique pour cet AdReel — n'affecte pas ton contenu (titres, textes, témoignages), qui reste dans la langue où tu l'as écrit. Les packs liés depuis cet AdReel suivent automatiquement ce choix.",
      bgColorAppearance: "Couleur de fond de la page publique de cet AdReel. Vérifie le contraste avec la couleur du texte pour rester lisible.",
      textColorAppearance: "Couleur du texte principal de la page publique de cet AdReel.",
    },
    github: {
      ghOwner: "Ton nom d'utilisateur ou d'organisation GitHub — visible dans l'URL de ton repo (github.com/OWNER/repo).",
      ghRepo: "Le nom du dépôt GitHub où ce site est hébergé — visible dans l'URL (github.com/owner/REPO).",
      ghBranch: "La branche du dépôt à lire et publier — \"main\" dans la grande majorité des cas, à ne changer que si ton repo utilise un nom de branche différent.",
      ghToken: "Un token d'accès personnel GitHub (\"Fine-grained\", limité à ce seul dépôt) qui autorise ce backstage à publier à ta place. Jamais sauvegardé — à recoller à chaque session.",
    },
    content: {
      formspreeEndpoint: "L'URL de ton formulaire Formspree — nécessaire uniquement si tu ajoutes un bloc \"Contact\" à une page. Sans ça, ce bloc n'affichera rien côté public.",
      blockAlign: "Position de ce bloc sur la page publique. S'applique uniquement si le bloc ne contient qu'un seul élément (une image) ; avec plusieurs images, elles s'affichent en grille quel que soit ce réglage.",
      headerTagline: "Courte phrase affichée sous ton logo (ou ton nom en toutes lettres si tu n'as pas de logo) — ta spécialité ou positionnement en une ligne.",
      headerLogo: "Ton logo, affiché en haut de la page. Sans logo, ton nom s'affiche en toutes lettres à la place.",
      headerContactEmail: "Affiché en bas de page si renseigné — indépendant du bloc \"Contact\" (formulaire), qui est optionnel.",
      headerWebsite: "Ton site web, affiché en bas de page si renseigné.",
      bioPhoto: "Photo affichée à côté de ton texte de présentation, dans ses proportions réelles (pas de recadrage forcé).",
      bioText: "Ton texte de présentation. Sépare les paragraphes par une ligne vide pour qu'ils s'affichent distinctement.",
      tracksBlockSelector: "Ce bloc affiche les morceaux sélectionnés ici, dans cet ordre, sur la page publique. Le contenu de chaque morceau (fichiers, description) se gère dans la Bibliothèque — ici tu choisis juste lesquels et dans quel ordre.",
      trackOverride: "Coche pour donner à ce morceau un titre/texte différent uniquement pour cet AdReel, sans toucher à la version de référence dans la Bibliothèque — utile par ex. pour une version dans une autre langue. Décoché, le texte de la Bibliothèque s'affiche tel quel.",
      videoLink: "Un lien YouTube ou Vimeo s'intègre automatiquement en vignette cliquable sur la page publique. Un autre type de lien (Dropbox, etc.) s'affiche comme un simple lien externe.",
      videoThumbnail: "Image affichée à la place de la vignette par défaut (générée automatiquement pour YouTube, absente sinon). Optionnel.",
    },
    misc: {
      feedbackBtn: "Envoie un message directement à Jules-Antoine — bugs, confusions, idées, ce qui t'a plu ou pas. Pas besoin d'être structuré.",
      backstageBgColor: "Change uniquement le fond de cet écran d'édition, pour ton confort visuel — n'a aucun effet sur ce que voient tes visiteurs. Mémorisé sur cet ordinateur seulement.",
      modeTestToggle: "Coche pendant que tu testes toi-même l'outil (démonstration, vérification) — tes actions ne compteront pas dans les statistiques d'usage réel des testeurs. Décoche pour ton usage normal.",
    },
  },
  en: {
    library: {
      trackMode: "Determines how this track behaves for the listener: Static for a single track, Vertical layering for layers that build up with intensity, Randomized vertical layering for variation on every listen, Sequential for an intro / segments / outro flow.",
      loopableStatic: "Check if this static track should loop continuously (ambience). Unchecked, it plays once and stops — suited to a theme or credits.",
      bpmMeasuresVerticalRandom: "This track's tempo and time signature, used to set the loop grid. Required here because this mode draws random layers that must stay synced to the beat.",
      loopPointsVerticalRandom: "These markers define where the loop starts and ends in the file. All layers (fixed and alternatives) must have exactly the same duration to stay in sync.",
      defaultLoopCount: "How many times the loop plays by default when the public page opens. Visitors can change this themselves — it's only a starting point.",
      bpmMeasuresSequential: "This track's tempo and time signature. They determine the planned length (in bars) of the intro and each segment — see below.",
      segmentSlotsSection: "Slots chained in the defined order (1, 2, 3, ... then back to the first), looping until the outro. Each slot can have several alternatives: one is drawn at random each time playback reaches that slot, rather than fixed content. At least one is needed for the track to be playable.",
      slotRepeatCount: "How many times this slot replays (drawing a new alternative each time) before moving to the next one in the chain. 1 by default — raise it for an AABA-like structure where the same slot needs to run several times in a row.",
      slotContentSource: "A slot can either have its own content, or duplicate (reference) another slot's pool that's already defined — useful for an AABA-like structure without loading the same files into memory twice. Repeat-avoidance is then shared between the two occurrences.",
      loopEngine: "Simple cuts and restarts the file instantly on every loop (fine for a loop that's already perfectly seamless). Quantized allows a smoother, tempo-locked transition, with a sound tail that keeps ringing while the next loop has already started.",
      bpmMeasuresQuantized: "This track's tempo and time signature, needed to align the quantized loop to the rhythmic grid instead of cutting at an arbitrary sample.",
      loopPointsQuantized: "These markers define the intro (played once), the loop, and the tail that overlaps as the next loop starts.",
      trackDescription: "Text shown on the public page under this track, visible when the visitor expands it. Select text then Cmd+K to insert a link.",
      normalizeVolume: "Automatically corrects volume differences between this track's files at conversion time (RMS measurement). Useful if your layers or alternatives come from different sessions and play back at uneven levels.",
      fixedLayers: "The layers that play on every loop cycle, without exception — this is where the intro and rhythmic backbone of the track live. They must all have the same duration as the random groups below.",
      randomGroups: "Each group randomly draws one of its alternatives on every loop cycle — this is what makes the track never sound exactly the same twice. A group can have just one alternative if you simply want to reserve the slot for later.",
      groupContentSource: "A group can either have its own content, or duplicate (reference) another group's pool that's already defined — avoids loading the same files into memory twice if two groups need to vary identically. Repeat-avoidance is then shared between the two.",
      batchDropSequential: "Drop several files at once: their role (intro / segment / outro) is guessed from the filename. Double-check with each block's \"Role\" selector afterwards, and fix it if needed.",
      introSection: "Plays once, right at the start of the track, before the random segment draw begins.",
      outroSection: "Only triggers if the visitor clicks \"Go to ending\" on the public side. Without an outro set, this button simply lets the current segment run to its natural end.",
      layersVertical: "This track's layers, from calmest to most intense — this order determines what gets added as the visitor increases the intensity on the public page.",
      stingers: "Short sounds the visitor can trigger manually during playback (e.g. a hit, an alert sting), layered on top of the ongoing music — they don't affect the main loop.",
      implementationNote: "Free note for your own use, reused as-is in the pack's implementation sheet (Packs tab). Can contain engine-specific jargon if you want (e.g. a suggested RTPC) — unlike the rest of the sheet, which is generated in neutral language.",
    },
    packs: {
      packIllustration: "Main image shown at the top of this pack's public page.",
      packWatermark: "Decorative background image shown as a transparent overlay behind all the page content — purely aesthetic, optional.",
      packPresentation: "Presentation text shown on the pack's public page, above the track list, when this pack is linked to a French AdReel. Select text then Cmd+K to insert a link.",
      packPresentationEn: "English version of the text above, shown when this pack is linked to an English AdReel. If one of the two languages isn't filled in, the other is shown by default.",
      packBuyable: "Shows a buy button on the pack's public page. No real payment is processed today — the link can point to something else in the meantime (email, form) if needed.",
      packVideoTestMode: "Adds a button to test a YouTube/Vimeo video: embedded right on the page if the visitor has a single screen, or in a separate detachable window if they have several. Muted by default (the visitor can turn sound back on), so the visitor can test your tracks live against it while watching.",
      implementationSkills: "Global setting for the whole site, not per pack. Check the software you're proficient with (Wwise, FMOD, Unity, Unreal): a message mentioning it appears on each pack's public page, listing only the checked ones. No box checked = no message shown.",
      implementationSheetBtn: "Generates on the fly a document (text + JSON) describing the musical behavior of each track in this pack in neutral language — number of layers, intensity thresholds, BPM, loop points, intro/segment/outro structure depending on mode. Nothing is stored or published, only generated the moment you click.",
      collectionIllustration: "Main image shown at the top of this collection's public page.",
      collectionPresentation: "Presentation text shown on the collection's public page, above the list of packs it contains, when linked to a French AdReel.",
      collectionPresentationEn: "English version of the text above. If one of the two languages isn't filled in, the other is shown by default.",
      collectionPacks: "The packs included in this collection, in the order they're shown on its public page. The same pack can belong to several collections.",
      packAppearance: "Background and text colors specific to this pack's page — independent from those of the AdReel linking to it.",
      packTracks: "The library tracks included in this pack, in the order they're shown on its public page.",
    },
    appearance: {
      publishLang: "The public interface language for this AdReel — doesn't affect your own content (titles, texts, testimonials), which stays in the language you wrote it in. Packs linked from this AdReel automatically follow this choice.",
      bgColorAppearance: "Background color of this AdReel's public page. Check the contrast against the text color to stay readable.",
      textColorAppearance: "Main text color of this AdReel's public page.",
    },
    github: {
      ghOwner: "Your GitHub username or organization — visible in your repo's URL (github.com/OWNER/repo).",
      ghRepo: "The name of the GitHub repository hosting this site — visible in the URL (github.com/owner/REPO).",
      ghBranch: "The repo branch to read from and publish to — \"main\" in the vast majority of cases, only change it if your repo uses a different branch name.",
      ghToken: "A GitHub personal access token (\"Fine-grained\", scoped to this one repository) that lets this backstage publish on your behalf. Never saved — paste it in again each session.",
    },
    content: {
      formspreeEndpoint: "Your Formspree form URL — only needed if you add a \"Contact\" block to a page. Without it, that block will show nothing on the public side.",
      blockAlign: "This block's position on the public page. Only applies if the block contains a single item (one image); with several images, they're shown as a grid regardless of this setting.",
      headerTagline: "Short line shown under your logo (or your spelled-out name if you don't have one) — your specialty or positioning in one sentence.",
      headerLogo: "Your logo, shown at the top of the page. Without one, your name is shown spelled out instead.",
      headerContactEmail: "Shown at the bottom of the page if filled in — independent from the \"Contact\" block (form), which is optional.",
      headerWebsite: "Your website, shown at the bottom of the page if filled in.",
      bioPhoto: "Photo shown next to your bio text, in its real proportions (no forced cropping).",
      bioText: "Your bio text. Separate paragraphs with a blank line so they display as distinct blocks.",
      tracksBlockSelector: "This block shows the tracks selected here, in this order, on the public page. Each track's content (files, description) is managed in the Library — here you're just choosing which ones and in what order.",
      trackOverride: "Check to give this track a different title/text just for this AdReel, without touching the reference version in the Library — useful e.g. for a version in another language. Unchecked, the Library text is shown as-is.",
      videoLink: "A YouTube or Vimeo link automatically embeds as a clickable thumbnail on the public page. Any other kind of link (Dropbox, etc.) shows as a plain external link instead.",
      videoThumbnail: "Image shown instead of the default thumbnail (auto-generated for YouTube, absent otherwise). Optional.",
    },
    misc: {
      feedbackBtn: "Sends a message straight to Jules-Antoine — bugs, confusing bits, ideas, what you liked or didn't. No need to be structured about it.",
      backstageBgColor: "Only changes the background of this editing screen, for your own visual comfort — has no effect on what your visitors see. Remembered on this computer only.",
      modeTestToggle: "Check while you're testing the tool yourself (demo, verification) — your actions won't count toward real testers' usage stats. Uncheck for normal use.",
    },
  },
};
